### ISSUE TITLE
What's the interpreter name?

### ISSUE THREAD

**Issue by 3oheicrw-alter-ego** [slang-lang/slang#5]
What's the exact name of the language, too?

`#!/usr/local/bin/webscript`

https://github.com/madelmann/moviebase/blob/main/SyntaxCheck.os

So the interpreter is `webscript`. Is `webscript` as a name has anything to do with ObjectiveScript or Slang? The way you named it is so funny. There is no rules at all!

**Comment by madelmann** [comment]
Hi,

webscript is simple script that checks if the current user is the webserver (in my case Apache) and adds the library path and the content header to the HTTP reply. This is/was necessary because the Slang interpreter is executed as a CGI script from within Apache. But you are right, I should have added it to the Slang repository. My fault, thanks for pointing it out.

#!/bin/bash

COMMAND="slang"
LIBRARY="/usr/local/share/slang/Library"
USER=`whoami`

if [ ${USER} == "www-data" ]; then
        echo -e "Content: text/html\n"
fi

${COMMAND} --library ${LIBRARY} $*
